INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '2012-01-01');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('María', 'Gómez', 'maria.gomez@example.com', '2012-02-15');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Carlos', 'López', 'carlos.lopez@example.com', '2012-03-10');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Ana', 'Rodríguez', 'ana.rodriguez@example.com', '2012-04-22');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Luis', 'Martínez', 'luis.martinez@example.com', '2012-05-18');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Laura', 'Sánchez', 'laura.sanchez@example.com', '2012-06-07');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Pedro', 'García', 'pedro.garcia@example.com', '2012-07-14');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Sofía', 'Hernández', 'sofia.hernandez@example.com', '2012-08-03');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Javier', 'González', 'javier.gonzalez@example.com', '2012-09-30');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Paula', 'Torres', 'paula.torres@example.com', '2012-10-25');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Alejandro', 'Vargas', 'alejandro.vargas@example.com', '2012-11-12');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Valentina', 'Castro', 'valentina.castro@example.com', '2012-12-06');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Diego', 'Ramírez', 'diego.ramirez@example.com', '2013-01-17');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Camila', 'Acosta', 'camila.acosta@example.com', '2013-02-09');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Mateo', 'Rojas', 'mateo.rojas@example.com', '2013-03-28');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Isabella', 'Vargas', 'isabella.vargas@example.com', '2013-04-13');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Daniel', 'Muñoz', 'daniel.munoz@example.com', '2013-05-22');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Lucía', 'Aguilar', 'lucia.aguilar@example.com', '2013-06-02');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Emilio', 'López', 'emilio.lopez@example.com', '2013-07-11');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Mariana', 'Ortega', 'mariana.ortega@example.com', '2013-08-24');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Benjamín', 'Soto', 'benjamin.soto@example.com', '2013-09-19');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Catalina', 'Fernández', 'catalina.fernandez@example.com', '2013-10-07');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Sebastián', 'Silva', 'sebastian.silva@example.com', '2013-11-30');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Antonella', 'Molina', 'antonella.molina@example.com', '2013-12-12');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Felipe', 'Guzmán', 'felipe.guzman@example.com', '2014-01-05');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Andrés', 'Herrera', 'andres.herrera@example.com', '2014-02-18');
INSERT INTO usuarios (nombre, apellido, email, created_at) VALUES ('Valeria', 'Navarro', 'valeria.navarro@example.com', '2014-03-14');
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Diez negritos', 'Agatha Christie','misterio', 25);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Asesinato en el Orient Express', 'Agatha Christie','misterio', 12);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Tres ratones ciegos', 'Agatha Christie','misterio', 13);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Muerte en el Nilo', 'Agatha Christie','misterio', 10);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El asesinato de Roger Acroyd', 'Agatha Christie','misterio', 11);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Matar es fácil', 'Agatha Christie','misterio', 9);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('La ratonera', 'Agatha Christie','misterio', 15);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Cita con la muerte', 'Agatha Christie','misterio', 16);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Un cadáver a la Biblioteca', 'Agatha Christie','misterio', 14);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El misterioso señor Brown', 'Agatha Christie','misterio', 13);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Estudio en escarlata', 'Arthur Conan Doyle','misterio', 9);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El signo de los cuatro', 'Arthur Conan Doyle','misterio', 8);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Las aventuras de Sherlock Holmes', 'Arthur Conan Doyle','misterio', 10);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Las memorias de Sherlock Holmes', 'Arthur Conan Doyle','misterio', 5);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El perro de los Baskerville', 'Arthur Conan Doyle','misterio', 12);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El regreso de Sherlock Holmes', 'Arthur Conan Doyle','misterio', 10);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El valle del miedo', 'Arthur Conan Doyle','misterio', 8);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El sabueso de los Baskerville', 'Arthur Conan Doyle','misterio', 7);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('La aventura de la casa vacía', 'Arthur Conan Doyle','misterio', 6);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El problema final', 'Arthur Conan Doyle','misterio', 4);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El problema final', 'Arthur Conan Doyle','misterio', 4);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('HP Lovecraft completa', 'HP Lovecraft','terror', 25);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El hombre de la rosa', 'Umberto Eco','historica', 10);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El medico', 'Noah Gordon','historica', 20);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Los pilares de la tierra', 'Ken Follett','historica', 14);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Yo, Claudio', 'Robert Graves','historica', 3);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('El capitán Alatriste', 'Arturo Perez-Reverte','historica', 15);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Africanus', 'Santiago Posteguillo','historica', 4);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('En la corte del lobo', 'Hilary Mantel','historica', 6);
INSERT INTO libros (titulo, autor,genero, cantidad_libros) VALUES ('Sinuhé el egipcio', 'Mika Waltari','historica', 5);
