INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Juan', 'Pérez', 'juan.perez@example.com', '2012-01-01','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Javier', 'Java', 'javi.java@example.com', '2012-02-15','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Carlos', 'López', 'carlos.lopez@example.com', '2012-03-10','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Ana', 'Rodríguez', 'ana.rodriguez@example.com', '2012-04-22','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Luis', 'Martínez', 'luis.martinez@example.com', '2012-05-18','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Laura', 'Sánchez', 'laura.sanchez@example.com', '2012-06-07','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Pedro', 'García', 'pedro.garcia@example.com', '2012-07-14','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Sofía', 'Hernández', 'sofia.hernandez@example.com', '2012-08-03','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Javier', 'González', 'javier.gonzalez@example.com', '2012-09-30','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Paula', 'Torres', 'paula.torres@example.com', '2012-10-25','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Alejandro', 'Vargas', 'alejandro.vargas@example.com', '2012-11-12','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Valentina', 'Castro', 'valentina.castro@example.com', '2012-12-06','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Diego', 'Ramírez', 'diego.ramirez@example.com', '2013-01-17','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Camila', 'Acosta', 'camila.acosta@example.com', '2013-02-09','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Mateo', 'Rojas', 'mateo.rojas@example.com', '2013-03-28','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Isabella', 'Vargas', 'isabella.vargas@example.com', '2013-04-13','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Daniel', 'Muñoz', 'daniel.munoz@example.com', '2013-05-22','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Lucía', 'Aguilar', 'lucia.aguilar@example.com', '2013-06-02','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Emilio', 'López', 'emilio.lopez@example.com', '2013-07-11','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Mariana', 'Ortega', 'mariana.ortega@example.com', '2013-08-24','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Benjamín', 'Soto', 'benjamin.soto@example.com', '2013-09-19','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Catalina', 'Fernández', 'catalina.fernandez@example.com', '2013-10-07','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Sebastián', 'Silva', 'sebastian.silva@example.com', '2013-11-30','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Antonella', 'Molina', 'antonella.molina@example.com', '2013-12-12','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Felipe', 'Guzmán', 'felipe.guzman@example.com', '2014-01-05','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Andrés', 'Herrera', 'andres.herrera@example.com', '2014-02-18','');
INSERT INTO usuarios (nombre, apellido, email, created_at,foto) VALUES ('Valeria', 'Navarro', 'valeria.navarro@example.com', '2014-03-14','');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Diez negritos', 'Agatha Christie','misterio',10, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Asesinato en el Orient Express', 'Agatha Christie','misterio',5,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Tres ratones ciegos', 'Agatha Christie','misterio',4,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Muerte en el Nilo', 'Agatha Christie','misterio',5,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El asesinato de Roger Acroyd', 'Agatha Christie','misterio',8,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Matar es fácil', 'Agatha Christie','misterio',7,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('La ratonera', 'Agatha Christie','misterio',6,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Cita con la muerte', 'Agatha Christie','misterio',5,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Un cadáver a la Biblioteca', 'Agatha Christie','misterio',7, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El misterioso señor Brown', 'Agatha Christie','misterio',5,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Estudio en escarlata', 'Arthur Conan Doyle','misterio',8, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El signo de los cuatro', 'Arthur Conan Doyle','misterio',6,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Las aventuras de Sherlock Holmes', 'Arthur Conan Doyle','misterio',1, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Las memorias de Sherlock Holmes', 'Arthur Conan Doyle','misterio',2,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El perro de los Baskerville', 'Arthur Conan Doyle','misterio',3, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El regreso de Sherlock Holmes', 'Arthur Conan Doyle','misterio',4, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El valle del miedo', 'Arthur Conan Doyle','misterio',8, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El sabueso de los Baskerville', 'Arthur Conan Doyle','misterio',8,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('La aventura de la casa vacía', 'Arthur Conan Doyle','misterio',10,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El problema final', 'Arthur Conan Doyle','misterio',8, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El problema final', 'Arthur Conan Doyle','misterio',7,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('HP Lovecraft completa', 'HP Lovecraft','terror',6, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El hombre de la rosa', 'Umberto Eco','historica',7, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El medico', 'Noah Gordon','historica',5, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Los pilares de la tierra', 'Ken Follett','historica',6, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Yo, Claudio', 'Robert Graves','historica',4, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('El capitán Alatriste', 'Arturo Perez-Reverte','historica',7, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Africanus', 'Santiago Posteguillo','historica',3, '');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('En la corte del lobo', 'Hilary Mantel','historica',2,'');
INSERT INTO libros (titulo, autor,genero,cantidad_libros,foto) VALUES ('Sinuhé el egipcio', 'Mika Waltari','historica',2,'');
INSERT INTO prestamos (fecha_entregar, fecha_devolver, referencia,usuario_id) VALUES ('2023-06-01', '2023-06-21','Diez negritos', 1);
INSERT INTO lineas_prestamos (cantidad_prestada, libro_id, prestamo_id) VALUES ( 1,1, 1);
INSERT INTO lineas_prestamos (cantidad_prestada, libro_id, prestamo_id) VALUES ( 1,2, 2);
